## ******************************************************************************
## This source code is licensed under the MIT license found in the
## LICENSE file in the root directory of this source tree.
## ******************************************************************************

name: format
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check-code-formatting:
    name: Code Formatting
    runs-on: ubuntu-24.04  # comes with clang-format v18
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Check format of `collective` directory
      run: |
        find collective -type f \( -name "*.cpp" -o -name "*.h" \) -print0 |
          xargs -0L1 clang-format -style=file --dry-run -Werror

    - name: Check format of `helper` directory
      run: |
        find helper -type f \( -name "*.cpp" -o -name "*.h" \) -print0 |
          xargs -0L1 clang-format -style=file --dry-run -Werror

    - name: Check format of `include` directory
      run: |
        find include -type f \( -name "*.cpp" -o -name "*.h" \) -print0 |
          xargs -0L1 clang-format -style=file --dry-run -Werror

    - name: Check format of `runner` directory
      run: |
        find runner -type f \( -name "*.cpp" -o -name "*.h" \) -print0 |
          xargs -0L1 clang-format -style=file --dry-run -Werror

    - name: Check format of `synthesizer` directory
      run: |
        find synthesizer -type f \( -name "*.cpp" -o -name "*.h" \) -print0 |
          xargs -0L1 clang-format -style=file --dry-run -Werror

    - name: Check format of `topology` directory
      run: |
        find topology -type f \( -name "*.cpp" -o -name "*.h" \) -print0 |
          xargs -0L1 clang-format -style=file --dry-run -Werror
